### ISSUE TITLE
Project Can't Open

### ISSUE THREAD

**Issue by bangiqi** [kemalekren/Sample-Custom-TableView-Project-#1]
Project Can't Open in XCode 9
![screen shot 2018-04-06 at 4 59 41 pm](https://user-images.githubusercontent.com/2718451/38415532-015105be-39bc-11e8-8d43-9d39757a2737.png)

**Comment by kemalekren** [comment]
Let me try to fix this issue.
I use Xcode 9.3 and swift 4 and i try to open this another computer it worked well can you try again one more time?
Is your xcode version updated?

**Comment by kemalekren** [comment]
I use Xcode 9.3 and swift 4 and i try to open this another computer it worked well can you try again one more time?

**Comment by kemalekren** [comment]
According to not get any answer from you i'll close this issue.
